#! /bin/zsh
#
# syntax: nskc cmd [prod] [cluster]
# nskc list ...
# nskc kubeconfig ...
#

0=${(%):-%x}

function _nskc_usage {
    echo 'usage: nskc {list|config} [prod] [cluster...]' >&2
}

function _nskc_cluster_list {
    typeset -a _ncl
    _ncl="${(@f)$(
        if ! (( $# )) ; then
            nsk cluster list
        else
            for i in "$@" ; do
                nsk cluster list -n "$i"
            done
        fi | sed 's/  */,/g' | cut -d, -f1-4
        )}"
    return _ncl
}

function _nskc_cluster_kubeconfig {
    if ! (( $# )) ; then
        set -- `kcf`
    fi

    for i in "$@" ; do
        OUTFILE=$(mktemp /tmp/"$i"-XXXXXX)
        nsk cluster kubeconfig -n "$i" --dest $OUTFILE
        kcf -a -F $OUTFILE
        rm -f $OUTFILE
    done
}

function nskc {
    if [[ $# == 0 ]]; then
        cmd=usage
    else
        cmd=$1 ; shift
    fi

    if [ "$1" = "prod" ] ; then
        export NSK_PROFILE=prod
        shift
    fi

    case $cmd in
        l|ls|list)
            echo $(_nskc_cluster_list "$@") | tv
            ;;

        c|kc|config|kubeconfig)
            _nskc_cluster_kubeconfig "$@"
            kcf
            ;;

        *)
            _nskc_usage
            return 2
            ;;
    esac
}

nskc "$@"
