repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args:
          - --shell=ksh
          - --external-sources
          - --exclude=SC1091        # ignore `Not following` in container
        types: []
        files: |
          (?x)^(
            dot\.z.*|
            zshell/_z.*|
            configure
          )
