#! /bin/zsh
#
# List machines that I have created/am owner of.
# Outputs a csv format that can be run through csvlook, in the csvkit package.
#

emulate -L zsh -o pipe_fail -o err_return

print "hostname,Private IP,instance-id,HW Type,expiry";
tsh ls --format=json "$@"                | \
    jq -r '.[]
           | [ .spec.hostname,
               ( .spec.cmd_labels |
                   .ip_private.result,
                   .aws_instance_id.result,
                   .hwtype.result[:7]
               ),
               .metadata.expires[:10]
             ]
           | @csv'
