#! /bin/zsh
#
# Find my one machine and connect to it.   You can parameterise and specify
# additional search parameters (use tsw labels to find possible search labels)
# to narrow down to a single machine.
#

emulate -L zsh -o pipe_fail -o err_return

set -- $@ "aws/Owner=$USER@zscaler.com"

if [[ $(tsh ls --format=json "$@"  | jq length) == 1 ]]; then
    tsh ssh $(tsh ls --format=json "$@"    | \
              jq -r '.[].spec.hostname')
else
    _tsw_goto "$@"
fi
