#! /bin/zsh

_vboxlist() {
    case $# in
    0)  VBoxManage list vms | sed -e 's/"\(.*\)" {\(.*\)}/\2	\1/' ;;
    *)
        args=$1 ; shift
        for i in "$@" ; do
            args="$args|$i"
        done
        VBoxManage list vms | grep -E -i "$args" | sed 's/.*{\(.*\)}/\1/'
        ;;
    esac
}

_vboxuninstalluser() {
    rm -rf ~/Library/VirtualBox
}

_vboxuninstallroot() {
    sudo rm -rf /Applications/VirtualBox.app
    sudo rm -rf /Library/Applications\ Support/VirtualBox
    kextstat | awk '/virtualbox/ { print $6 }' | while read -r x ; do
        sudo kextunload -b "$x"
    done
    sleep 1
    kextstat | awk '/virtualbox/ { print $6 }' | while read -r x ; do
        sudo kextunload -b "$x"
    done
    sudo kextcache -prune-staging
}

vb() {
    case "$1" in
    .help)
        echo "usage: vb [ .list | .destroyall | .renameDisk <disk> | ... " >&2
        ;;
    .list)  
        shift;
        _vboxlist "$*"
        ;;
    .destroyall)
        _vboxuninstalluser
        _vboxuninstallroot
        ;;
    .renameDisk)
        shift
        VBoxManage internalcommands sethduuid "$@"
        ;;
    *)
        VBoxManage "$*"
        ;;
    esac
}
