#! /bin/zsh

if ! brew -v >/dev/null 2>&1 ; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    rm -rf /Library/Caches/Homebrew/*
fi

if [[ -f ./$(uname -s)/Brewfile ]] ; then
    pushd "$(uname -s)" || { log --error Directory "$(uname -s)" not found; exit 1; }
    brew bundle install
    popd || { log --error Directory "$(uname -s)" not found; exit 1; }
fi

exit
