#! /bin/sh -x

# this work is partial
defaults write com.apple.finder AppleShowAllFiles   -string YES
defaults write com.apple.finder QuitMenuItem        -bool true

defaults write com.apple.dock   autohide                         -bool true
defaults write com.apple.dock   magnification                    -bool true
defaults write com.apple.dock   minimize-to-application          -bool true
defaults write com.apple.dock   largesize                        -float 72
defaults write com.apple.dock   showMissionControlGestureEnabled -bool true
defaults write com.apple.dock   wvous-bl-corner			 -int  5
defaults write com.apple.dock   wvous-br-corner			 -int  6

defaults write com.apple.AppleMultitouchTrackpad                    \
                                Clicking                         -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad   \
                                Clicking                         -bool true
defaults write org.cups.PrintingPrefs UseLastPrinter             -bool False

# /Applications/RDM.app/Contents/MacOS/SetResX -w 2880 -h 1800 -s 2.0

killall Finder Dock

nvram boot-args='-v'
