#! /bin/sh
#
# Set background color.
pkill swaybg
swaybg -c '#040404'             \
       -i "/home/kannan/Pictures/2017-06-09-assets-natgeotv.fnghub.com:POD:7871.jpg" \
       -m fit                   \
>/dev/null 2>&1 &


# Launch a panel such as yambar or waybar.
waybar >/dev/null 2>&1 &

conky --config=$HOME/.config/conky/calendars.conky &
conky --config=$HOME/.config/conky/sunrise-sunset.conky &
conky --config=$HOME/.config/conky/sysPerf.conky &

# Lock screen after 5 minutes; turn off display after another 5 minutes.
#
swayidle -w                                             \
	 timeout 300 'swaylock -e -f -c 000000'             \
	 timeout 600 'wlopm --off \*'                       \
	      resume 'wlopm --on \*'                        \
	before-sleep 'swaylock -e -f -c 000000' >/dev/null 2>&1 &

test -x /usr/bin/betterbird && /usr/bin/betterbird >/dev/null 2>&1 &
test -x /usr/bin/firefox    && /usr/bin/firefox    >/dev/null 2>&1 &

test -x /usr/bin/wasistlos  && /usr/bin/wasistlos  >/dev/null 2>&1 &
test -x /usr/bin/whatsie    && /usr/bin/whatsie    >/dev/null 2>&1 &

if [[ -x /usr/bin/way-displays ]] ; then
    /usr/bin/way-displays >/dev/null 2>&1
else
    /usr/bin/foot 
fi
