#! /bin/zsh #
# shellcheck disable=SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

if test -z "${XDG_RUNTIME_DIR}" ; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    test -d ${XDG_RUNTIME_DIR} || mkdir ${XDG_RUNTIME_DIR}
    chmod 0700 ${XDG_RUNTIME_DIR}
fi

export ELECTRON_OZONE_PLATFORM_HINT=auto
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SCANNER="airscan:e1:HP Color LaserJet MFP M277c6 (142B9F)"

export SUDO_ASKPASS=$HOME/bin/sudo_askpass
export SUDO_ASKPASS_FIFO=${SUDO_ASKPASS_FIFO:-"/tmp/sudo-askpass-$(id -u -n)"}
export SSH_AUTH_SOCK=$HOME/.1password/agent.sock
