#! /bin/zsh
#
# shellcheck disable=SC1110,SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

typeset -F SECONDS

prtiming() {
    #
    # set   terminal    qt 0 font "SF Mono,12" noenhanced
    # unset key
    # set   xrange      [-.05:.6]
    # unset ytics
    # set   yzeroaxis
    # set   yrange      [-1:19]
    # set   style arrow 2 nohead 			      \
    #                   linecolor rgb "#56b4e9" linewidth 5   \
    #		        dashtype solid size		      \
    #                   screen  0.020,15.000,90.000  fixed
    # plot 'data' using ($3):($0):(column(5)-column(3)):(0.0):yticlabel(2) \
    #	          with vector as 2,					   \
    #      'data' using ($3):($0):2 with labels right offset -1
    # pause -1
    #
    e="$3"
    e="${e:-$SECONDS}"
    if [ -t 0 ] ; then
        print -f ":[$$] %25s\t%8.6f -- %8.6f\t%8.6f\n" "$1" "$2" "$e" $(( e - $2)) | tee -a /tmp/timings.dat
    fi
}
plotShellStats() {
    local _PSS_DATA=${DATAFILE:-$(mktemp /tmp/ziXXXXXX)}

    if ! [[ -s "$_PSS_DATA" ]] ; then
        grep $$ /tmp/timings.dat > $_PSS_DATA
    fi

    local _PSS_XMAX=$(tail -1 $_PSS_DATA | cut -w -f5)
    _PSS_XMAX=$(( _PSS_XMAX + 0.02 ))

    local _PSS_YMAX=$(wc -l $_PSS_DATA | cut -w -f2)
    _PSS_YMAX=$(( _PSS_YMAX + 1 ))

    gnuplot <<END_GNUPLOT
      set   terminal    qt 0 font "Monaco,12" noenhanced
      unset key

      set   xrange      [-.05:$_PSS_XMAS]

      unset ytics
      set   yzeroaxis
      set   yrange      [-1:$_PSS_YMAX]

      set   style arrow 2 nohead linecolor rgb "#56b4e9" linewidth 5 dashtype solid 
      set   style arrow 2 size screen  0.020,15.000,90.000

      # plot a vector from column(3), current row to column(5), current row
      # use column(2) as label, at column(3), current row, right offset from point
      #
      plot '$_PSS_DATA' using 3:0:(column(5)-column(3)):(0.0) with vector as 2,   \\
           ''           using 3:0:2 with labels right offset -1
      unset multiplot
      pause mouse
END_GNUPLOT
    if ! [[ "$DATAFILE" ]]; then
        rm -f "$_PSS_DATA"
    fi
}

0="${ZERO:-${${0:#$ZSH_ARGZERO}:-${(%):-%N}}}"
0="${${(M)0:#/*}:-$PWD/$0}"

#
# ZSH PARAMETERS

#
# Options that we care about
#
setopt AUTO_CD
setopt PUSHD_IGNORE_DUPS
setopt NO_NOMATCH
: setopt TYPESET_SILENT
setopt RM_STAR_SILENT
setopt AUTO_CONTINUE NOTIFY CLOBBER
setopt SH_NULLCMD
setopt PROMPT_SUBST
setopt SHARE_HISTORY EXTENDED_HISTORY
setopt EXTENDED_GLOB

#
# zstyle
#
zstyle ‘:completion:*’              verbose yes
zstyle ‘:completion:*:descriptions’ format ‘%B%d%b’
zstyle ‘:completion:*:messages’     format ‘%d’
zstyle ‘:completion:*:warnings’     format ‘No matches for: %d’
zstyle ‘:completion:*’              group-name ”

umask 022
