#! /bin/zsh #
# shellcheck disable=SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

typeset -xT INFOPATH infopath :
typeset -U PATH     path
typeset -U CDPATH   cdpath

# shellcheck disable=SC2034	# implicit zshism here
typeset -U MANPATH  manpath
typeset -U INFOPATH infopath

path+=( . .. ./bin ./sbin ../bin ../sbin )
infopath+=( ./info )

local _i
for _i in /usr/local            \
          /opt                  \
          /opt/homebrew         \
          /opt/homebrew/share   \
          $HOME/.local          \
          $HOME
do
    test -d "$_i"       || continue

    #
    # https://www.zsh.org/mla/users/2022/msg00300.html
    #
    test -d "$_i/bin"   && path[1,0]="$_i/bin"
    test -d "$_i/sbin"  && path[1,0]="$_i/sbin"
    test -d "$_i/man"   && manpath[1,0]="$_i/man"
    test -d "$_i/info"  && infopath[1,0]="$_i/info"
done
manpath+=( "" )

#
# golang 
#
path+=( "$(go env GOPATH)"/bin )

path+=( "$HOME/.krew" )

# shellcheck disable=SC2034	# implicit zshism here
cdpath=( . ..
         "$HOME"
         "$HOME/Desktop"
         "$HOME/Documents"
         "$HOME/Drives"
         /
         /Volumes
         /mnt
)

typeset -xT NETHACKOPTIONS nethackoptions ,
typeset -U  NETHACKOPTIONS nethackoptions
nethackoptions=(
    name=Croesus-val-hum-law
    color
    eight_bit_tty
    hilite_pet
    !mail
    rest_on_space
    showexp
    time
    !tutorial
    pickup_types='$"/?!='
    boulder=0
)
