#! /bin/zsh
#
# shellcheck disable=SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

# zmodload zsh/zprof
# zprof -c
autoload -Uz compinit
# From https://gist.github.com/ctechols/ca1035271ad134841284#gistcomment-2308206
# shellcheck disable=SC1072,SC1073
() {
  if (( $# )) ; then
    compinit && zcompile ${ZDOTDIR:-$HOME}/.zcompdump
  else
    compinit -C
  fi
} ${ZDOTDIR:-$HOME}/.zcompdump.zwc(N.mh+24)
#                                 
#                                 ││││││ └ implies st_mtime > 24hours back
#                                 │││││└── greater then
#                                 ││││└─── hours
#                                 │││└──── modify (st_mtime)
#                                 ││└───── plain files only
#                                 │└────── set NULL_GLOB for this call
#                                 └─────── shell glob
# https://zsh.sourceforge.io/Doc/Release/Expansion.html#Filename-Expansion, 
# section 14.8.7 Glob Qualifiers
#
# unicode u2500 ─
#         u2502 │
#         u2514 └

zstyle ':antidote:bundle' use-friendly-names 'yes'
for _25i in /usr/local/opt/antidote                    \
         /usr/share/zsh-antidote                    \
         /opt/homebrew/opt/antidote/share/antidote  \
         FAIL
do
    if [[ -d "$_25i" ]] ; then
        source "$_25i/antidote.zsh"
        break
    fi
done
if [[ $_25i = FAIL ]] ; then
    # unwarranted chumminess 
    echo 'antidote not found' >&2
fi

# Initialize a few things that OMZ did for you nicely...
local _ZSH_ANTIDOTE_HOME="$(antidote home)"
ZSH_CACHE_DIR="$(dirname "$_ZSH_ANTIDOTE_HOME")"/zshell

# ensure completions dir
mkdir -p "$ZSH_CACHE_DIR"/completions

(( ${fpath[(Ie)"$ZSH_CACHE_DIR/completions"]} )) || \
    fpath=("$ZSH_CACHE_DIR/completions" "${fpath[@]}")

# source <(antibody init)

if ! [[ -f ~/.zsh_plugins.zsh ]] ||
   ! [[ -d "$_ZSH_ANTIDOTE_HOME/ohmyzsh/ohmyzsh" ]] ; 
then
    antidote bundle <<PLUGINS_LIST >~/.zsh_plugins.zsh
        ohmyzsh/ohmyzsh path:lib/git.zsh
        ohmyzsh/ohmyzsh path:lib/correction.zsh
        ohmyzsh/ohmyzsh path:lib/completion.zsh
        ohmyzsh/ohmyzsh path:lib/compfix.zsh

        ohmyzsh/ohmyzsh path:plugins/git
	ohmyzsh/ohmyzsh path:plugins/gh
        ohmyzsh/ohmyzsh path:plugins/brew
        # ohmyzsh/ohmyzsh path:plugins/aws
        # ohmyzsh/ohmyzsh path:plugins/gcloud
        ohmyzsh/ohmyzsh path:plugins/tmux
        ohmyzsh/ohmyzsh path:plugins/docker
        # ohmyzsh/ohmyzsh path:plugins/vagrant
        ohmyzsh/ohmyzsh path:plugins/chucknorris
        ohmyzsh/ohmyzsh path:plugins/helm
        ohmyzsh/ohmyzsh path:plugins/kubectl

        wting/autojump  path:bin/autojump.zsh
        atuinsh/atuin

        zsh-users/zsh-completions
        zsh-users/zsh-autosuggestions
        zsh-users/zsh-syntax-highlighting
        zsh-users/zsh-history-substring-search

        kvaradhan3/dotFiles path:common/zshell/plugins/workplace
        # kvaradhan3/dotFiles path:common/zshell/plugins/nskc
        kvaradhan3/dotFiles path:common/zshell/plugins/batteryCharge
        kvaradhan3/dotFiles path:common/zshell/plugins/1p
        kvaradhan3/dotFiles path:common/zshell/plugins/emulators
        kvaradhan3/dotFiles path:common/zshell/plugins/log
        kvaradhan3/dotFiles path:common/zshell/plugins/utilities

        bigH/git-fuzzy      path:bin kind:path
        wfxr/forgit
        sindresorhus/pure   kind:fpath
PLUGINS_LIST
fi


#shellcheck source=/Users/kvaradhan/.zsh_plugins.zsh
source ~/.zsh_plugins.zsh

# shellcheck source=/Users/kvaradhan/.gitsy.zsh-theme
# source "${0:h}"/themes/gitsy.zsh-theme
source "${0:h}"/themes/pure.zsh-theme

# shellcheck disable=SC2034
COMPLETION_WAITING_DOTS="true" # used in lib/completion.zsh
# zprof
# zmodload -ui zsh/zprof
