#! /bin/zsh

case "$(uname -rv | tr '[:upper:]' '[:lower:]')" in
    *arch*)
        export AURDEST=/var/pacman/packages
        export AUR_PACMAN_AUTH="sudo --askpass"
        export AUR_PAGER=ranger
        export AUR_REPO=AUR
esac

# shellcheck disable=SC1072,SC1073
() {
    if [[ $# -gt 0 ]]
    then
        case "$(uname -rv | tr '[:upper:]' '[:lower:]')" in
        *darwin*)
            /usr/sbin/softwareupdate -l
            brew update >/dev/null 2>&-
            brew outdated
            ;;
        *ubuntu*|*darwin*)
            /usr/lib/update-notifier/apt-check -p
            ;;
        *centos*|*rhel*|*fedora*)
            yum list upgradable
            ;;
        *arch*)
            paclist AUR | aur vercmp
            checkupdates
            ;;
        *)
            printf "%s: unknown system %s (%s), updates check not done.\n" \
                   "$(basename "$0")" "$(uname -s)" "$(uname -r)"
            ;;
        esac
        antidote update
        touch -m "$@"
    fi
} $0(N.mh+192)

