#! /bin/zsh
#
# shellcheck disable=SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

typeset -xT INFOPATH infopath :
typeset -U PATH     path
typeset -U CDPATH   cdpath

# shellcheck disable=SC2034	# implicit zshism here
typeset -U MANPATH  manpath
typeset -U INFOPATH infopath

path+=( . .. ./bin ./sbin ../bin ../sbin )
infopath+=( ./info )

local _i
for _i in /usr/local     \
         /opt            \
         $HOME
do
    test -d "$_i"       || continue
    test -d "$_i/bin"   && path+=(     "$_i/bin"  )
    test -d "$_i/sbin"  && path+=(     "$_i/sbin" )
    test -d "$_i/man"   && manpath+=(  "$_i/man"  )
    test -d "$_i/info"  && infopath+=( "$_i/info" )
done
manpath+=( "" )

#
# golang 
#
path+=( "$(go env GOPATH)"/bin )

path+=( "$HOME/.krew" )

# shellcheck disable=SC2034	# implicit zshism here
cdpath=( . ..
         "$HOME"
         "$HOME/Desktop"
         "$HOME/Documents"
         "$HOME/Drives"
         /
         /Volumes
         /mnt
)

export NETHACKOPTIONS=eight_bit_tty,hilite_pet,rest_on_space,showexp,time,!mail,pickup_types='$"/?!=',boulder=0,name=Croesus,color

if [[ "$(uname -s)" = Linux ]]
then
    if test -z "${XDG_RUNTIME_DIR}" ; then
        export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
        test -d ${XDG_RUNTIME_DIR} || mkdir ${XDG_RUNTIME_DIR}
        chmod 0700 ${XDG_RUNTIME_DIR}
    fi

    export MOZ_ENABLE_WAYLAND=1
    export QT_QPA_PLATFORM=wayland
fi

if [[ "$(uname -s)" = Darwin ]]
then
    export HOMEBREW_PREFIX="/opt/homebrew";
    export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
    export HOMEBREW_REPOSITORY="/opt/homebrew";
    export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
    export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
    export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

    source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh
fi

export SSH_AUTH_SOCK=$HOME/.1password/agent.sock
