#! /bin/zsh

typeset -F SECONDS

prtiming() {
    #
    # set   terminal    qt 0 font "SF Mono,12" noenhanced
    # unset key
    # set   xrange      [-.05:.6]
    # unset ytics
    # set   yzeroaxis
    # set   yrange      [-1:19]
    # set   style arrow 2 nohead 			      \
    #                   linecolor rgb "#56b4e9" linewidth 5   \
    #		        dashtype solid size		      \
    #                   screen  0.020,15.000,90.000  fixed
    # plot 'data' using ($3):($0):(column(5)-column(3)):(0.0):yticlabel(2) \
    #	          with vector as 2,					   \
    #      'data' using ($3):($0):2 with labels right offset -1
    # pause -1
    #
    e="$3"
    e="${e:-$SECONDS}"
    if [ -t 0 ] ; then
        print -f ": %25s\t%8.6f -- %8.6f\t%8.6f\n" "$1" "$2" "$e" $(( e - $2))
    fi
}

#
fpath=(
        "$ZDOTDIR"
        "$ZDOTDIR_LOCAL"
        "$ZDOTDIR_LOCAL/functions"
        "$HOME/src/zsh-completions/src"
        "/usr/local/share/zsh-completions"
        "${fpath[@]}"
    )

typeset -xTU FPATH fpath :

autoload -Uz _path
autoload -Uz _cdpath

_path    . ..
_path -p /usr/local
_path -p "$HOME"
# _path -p "$(brew --prefix)"/opt/python/libexec
# _path -p "$(brew --prefix)"/opt/ruby

_cdpath
_cdpath -p . .. "$HOME"
_cdpath "$HOME"/Desktop  "$HOME"/Documents
_cdpath "$HOME"/Drives/* "$HOME"/Drives
_cdpath / /Volumes

umask 022
