#! /bin/zsh
#
# shellcheck disable=SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

0="${ZERO:-${${0:#$ZSH_ARGZERO}:-${(%):-%N}}}"
0="${${(M)0:#/*}:-$PWD/$0}"

#
# prereqs:
#   brew install go-jira
#   go install github.com/ankitpokhrel/jira-cli/cmd/jira@latest
#

export GOPRIVATE=github.com/netskope,github.com/netSkopePlatformEng,github.com/netskope-qe

#
# These zshisms expand globally.
#
alias -g .obs="-p OBS"
alias -g .open="-s all-open"
alias -g .backlog="-s backlog"
alias -g .epic="-t epic"
alias -g .ng="-l new-obs-repo"
alias -g .upd="-u '>='"
alias -g .cs='-S "openSprints()"'
alias -g .fs='-S "futureSprints()"'
alias -g .mine="-A 'currentuser()'"
alias -g .rmine="-R 'currentuser()'"

# alias new-obs-repo-all='jira list -q "$(jf .obs .open .ng) DESC" -t obs-list'
# alias new-obs-repo-epics='jira list -q "$(jf .obs .open .epic .ng) DESC" -t obs-list'

alias j-fzf='fzf --header-lines=1 --preview="jira clean {1}"'
