#! /bin/zsh
#
# shellcheck disable=SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

unalias -m '*'

# some useful aliases
alias c='clear'
alias h='fc -l'
alias jo='jobs -l'
alias m='$PAGER'

export CLICOLOR=
alias ls='ls -F'
alias ll='ls -laFo'
alias l='ls -l'

alias g='egrep -i'
alias qlp='/usr/bin/qlmanage -p'

alias p=pushd
alias pop=popd

alias rc='readlink current'
alias mkrc='$(ln -sf "$(pf -d .values)" current)'

alias tl='tmux list-sessions'
alias ta='tmux attach -t'

alias mv='nocorrect mv '
alias cp='nocorrect cp '
alias ln='nocorrect ln '

alias de-vt100="sed -e 's/\x1b\[[0-9;]*[mGKHF]//g'"

alias chrome='daemonize /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --auto-open-devtools-for-tabs'
alias ji="~/go/bin/jira"

#
# kubernetes Aliases
#
#source /usr/local/share/zsh/site-functions/_kubectl
alias ka='kubeadm'

alias ks='kubectl -n kube-system'
alias kn='kubectl -n'
alias k='kubectl'
#
alias -g .an='--all-namespaces'
alias -g .w='--watch'
alias -g del=delete
#
alias kl='kubectl logs -f'
alias kls='kubectl -n kube-system logs -f'
