#! /bin/zsh

if [ ! -t 0 ] ; then
    return 0
fi

syst=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "$syst" = 'linux' ] ; then
    if   grep -E -i 'ubuntu|debian'  /etc/os-release >/dev/null 2>&1 ; then
        syst=debian-linux
    elif grep -E -i 'centos|rhel|fedora' /etc/os-release >/dev/null 2>&1 ; then
        syst=redhat-linux
    elif grep -E -i 'archlinux'      /etc/os-release >/dev/null 2>&1 ; then
        syst=arch-linux
    else
        syst=unknown-linux
    fi
fi

case $syst in
darwin)
    if [[ $(( $(/usr/bin/stat -Lf %m "$0") + 2 * 24 * 60 * 60 )) -lt $(date +%s) ]] ; then
        /usr/sbin/softwareupdate -l
        brew update >/dev/null 2>&-
        brew outdated
    fi
    ;;
*-linux)
    if [[ $(( $(stat --format %Y  "$0") + 2 * 24 * 60 * 60 )) -lt $(date +%s) ]] ; then
        case $syst in
            debian-*)
                /usr/lib/update-notifier/apt-check -p
                ;;
            centos-*)
                yum list upgradable
                ;;
            arch-*)
		export AURDEST=/var/pacman/packages
		export AUR_PACMAN_AUTH="sudo --askpass"
		export AUR_PAGER=ranger
		export AUR_REPO=AUR

                paclist AUR | aur vercmp
                checkupdates
                ;;
            *)
                print "$(basename "$0"): unknown system $syst, updates check not done\n" >&2
                ;;
        esac
    fi
    ;;
esac
touch -m "$0"
