#! /bin/zsh
#
# prereqs:
#   brew install go-jira
#   go install github.com/ankitpokhrel/jira-cli/cmd/jira@latest
#

export GOPRIVATE=github.com/netskope,github.com/netSkopePlatformEng,github.com/netskope-qe
alias ji=~/go/bin/jira

#
# These zshisms expand globally.
#
alias -g .obs="-p OBS"
alias -g .open="-s all-open"
alias -g .backlog="-s backlog"
alias -g .epic="-t epic"
alias -g .ng="-l new-obs-repo"
alias -g .upd="-u '>='"
alias -g .cs='-S "openSprints()"'
alias -g .fs='-S "futureSprints()"'
alias -g .mine="-A 'currentuser()'"
alias -g .rmine="-R 'currentuser()'"

# alias new-obs-repo-all='jira list -q "$(jf .obs .open .ng) DESC" -t obs-list'
# alias new-obs-repo-epics='jira list -q "$(jf .obs .open .epic .ng) DESC" -t obs-list'

