#! /bin/zsh

typeset -F SECONDS

prtiming() {
    #
    # set   terminal    qt 0 font "SF Mono,12" noenhanced
    # unset key
    # set   xrange      [-.05:.6]
    # unset ytics
    # set   yzeroaxis
    # set   yrange      [-1:19]
    # set   style arrow 2 nohead 			      \
    #                   linecolor rgb "#56b4e9" linewidth 5   \
    #		        dashtype solid size		      \
    #                   screen  0.020,15.000,90.000  fixed
    # plot 'data' using ($3):($0):(column(5)-column(3)):(0.0):yticlabel(2) \
    #	          with vector as 2,					   \
    #      'data' using ($3):($0):2 with labels right offset -1
    # pause -1
    #
    e="$3"
    e="${e:-$SECONDS}"
    if [ -t 0 ] ; then
        print -f ": %25s\t%8.6f -- %8.6f\t%8.6f\n" "$1" "$2" "$e" $(( e - $2))
    fi
}

typeset -xT INFOPATH infopath :
typeset -U PATH     path
typeset -U CDPATH   cdpath

# shellcheck disable=SC2034	# implicit zshism here
typeset -U MANPATH  manpath
typeset -U INFOPATH infopath

path+=( . .. ./bin ./sbin ../bin ../sbin )
infopath+=( ./info )

for i in /usr/local     \
         /opt           \
         $HOME
do
    test -d "$i"       || continue
    test -d "$i/bin"   && path+=(     "$i/bin"  )
    test -d "$i/sbin"  && path+=(     "$i/sbin" )
    test -d "$i/man"   && manpath+=(  "$i/man"  )
    test -d "$/info"   && infopath+=( "$i/info" )
done
manpath+=( "" )

# shellcheck disable=SC2034	# implicit zshism here
cdpath=( . .. 
         "$HOME"
         "$HOME/Desktop"
         "$HOME/Documents"
         "$HOME/Drives"
         /
         /Volumes
         /mnt
)

umask 022
