#! /bin/zsh
#
# shellcheck disable=SC1110,SC2278,SC2298,SC2296,SC2299
# SC2086 (info): Double quote to prevent globbing and word splitting.
# SC2296 (error): Parameter expansions can't start with (. Double check syntax.
# SC2298 (error): ${${x}} is invalid. For expansion, use ${x}.
#        For indirection, use arrays, ${!x} or (for sh) eval.
# SC2278 (error): $0 can't be assigned in Ksh (but it does reflect the current function).
# SC2299 (error): Parameter expansions can't be nested. Use temporary variables.
#

typeset -F SECONDS

prtiming() {
    #
    # set   terminal    qt 0 font "SF Mono,12" noenhanced
    # unset key
    # set   xrange      [-.05:.6]
    # unset ytics
    # set   yzeroaxis
    # set   yrange      [-1:19]
    # set   style arrow 2 nohead 			      \
    #                   linecolor rgb "#56b4e9" linewidth 5   \
    #		        dashtype solid size		      \
    #                   screen  0.020,15.000,90.000  fixed
    # plot 'data' using ($3):($0):(column(5)-column(3)):(0.0):yticlabel(2) \
    #	          with vector as 2,					   \
    #      'data' using ($3):($0):2 with labels right offset -1
    # pause -1
    #
    e="$3"
    e="${e:-$SECONDS}"
    if [ -t 0 ] ; then
        print -f ": %25s\t%8.6f -- %8.6f\t%8.6f\n" "$1" "$2" "$e" $(( e - $2))
    fi
}

0="${ZERO:-${${0:#$ZSH_ARGZERO}:-${(%):-%N}}}"
0="${${(M)0:#/*}:-$PWD/$0}"

#
# ZSH PARAMETERS

#
# Options that we care about
#
setopt AUTO_CD
setopt PUSHD_IGNORE_DUPS
setopt NO_NOMATCH
: setopt TYPESET_SILENT
setopt RM_STAR_SILENT
setopt AUTO_CONTINUE NOTIFY CLOBBER
setopt SH_NULLCMD
setopt PROMPT_SUBST

#
# zstyle
#
zstyle ‘:completion:*’              verbose yes
zstyle ‘:completion:*:descriptions’ format ‘%B%d%b’
zstyle ‘:completion:*:messages’     format ‘%d’
zstyle ‘:completion:*:warnings’     format ‘No matches for: %d’
zstyle ‘:completion:*’              group-name ”

umask 022
